// Import all product images
import curdImg from "../asset/WEBSITE_ASSETS/CURD.avif";
import soyaImg from "../asset/WEBSITE_ASSETS/PLAIN_TOFU.jpg";
import soyaMilkImg from "../asset/WEBSITE_ASSETS/RAW_SOYA_MILK.jpg";
import vanillaImg from "../asset/WEBSITE_ASSETS/VANILLA_ICE_CREAM.jpg";
import chocolateImg from "../asset/WEBSITE_ASSETS/CHOCKLATE_SOYA_MILK.jpg";
import cheeseImg from "../asset/WEBSITE_ASSETS/PLAIN_CHEESE.jpg";
import yogurtImg from "../asset/WEBSITE_ASSETS/NATURAL_YOGURT.jpg";
import chakliImg from "../asset/WEBSITE_ASSETS/soya-chakli.jpg";
import herbalTofuImg from "../asset/WEBSITE_ASSETS/HARBAL_TOFU.jpg";
import p1 from "../asset/WEBSITE_ASSETS/CHEESE.jpg";
import p2 from "../asset/WEBSITE_ASSETS/RAW_MILK.avif";
import p3 from "../asset/WEBSITE_ASSETS/PANEER.jpg";
import p4 from "../asset/WEBSITE_ASSETS/YOGURT.jpeg";
import strawberryIceCreamImg from "../asset/WEBSITE_ASSETS/strawberry-ice-cream.jpg";

// All products data with IDs for routing
export const allProducts = [
  {
    id: "soya-milk",
    image: soyaMilkImg,
    name: "Soya Milk",
    unit: "250 gm",
    price: 100,
    description:
      "Soya Milk is a healthy and nutritious drink made from soya beans. It is rich in protein and calcium and is a good source of vitamins and minerals.",
    aboutProduct:
      "Our Soya Milk is crafted from premium soybeans, offering a nutritious and delicious alternative to dairy milk. Rich in protein, calcium, and essential nutrients, it's perfect for those seeking a healthy, lactose-free beverage option.",
    button: "ADD",
    category: "Milk",
    discount: 10,
    detailedDescription:
      "Tempayy Crumbles are a quick and easy way to PROTEIN UP your meals with taste and flavour. Just pan-toss the crumbles for a few minutes and add it to your salads, wraps, curries and anything else you can think of. Tempayy is a your saads, frey mied that is naturally packed with gut-friendly protein giving you a rare mix of nutrients that is super good for you.",
    benefits: [
      "Rich in protein and calcium",
      "Good source of vitamins and minerals",
      "Lactose-free",
      "Suitable for lactose-intolerant individuals",
    ],
    nutritionalInfo: {
      protein: "8g per 100ml",
      calcium: "100mg per 100ml",
      iron: "1mg per 100ml",
    },
    highlight: ["High protein", "Flavour Natural", "Lactose-free"],
    keyFeatures: [
      "2X more protein than Paneer, Dal and Protein Bars for the same calories",
      "10x less fat than Paneer",
      "A rich source of fibre",
      "Low Carb & Low Fat",
      "Gut-friendly",
      "Preservative Free",
    ],
    rating: 4.5,
    reviews: 100,
    subcategory: "Soya Milk",
    expire: "10 days",
    wigthType: ["250 gm", "500 gm", "1 kg"],
  },
  {
    id: "plain-soya-tofu",
    image: soyaImg,
    name: "Plain Soya Tofu",
    unit: "200 g",
    price: 100,
    description:
      "100% Veg Soya Paneer, Rich source of Protein and Iron, Low in fat and cholesterol free.",
    aboutProduct:
      "Our Plain Soya Tofu is a versatile and nutritious plant-based protein source. Made from premium soybeans, it offers a clean, neutral taste that adapts beautifully to any recipe while providing essential nutrients for a healthy diet.",
    button: "ADD",
    category: "Tofu",
    discount: 20,
    detailedDescription:
      "Our Plain Soya Tofu is crafted from premium soybeans, offering a rich source of plant-based protein and essential nutrients. This versatile ingredient is perfect for both cooking and direct consumption, providing a healthy alternative to traditional dairy products.",
    benefits: [
      "High in protein and iron",
      "Low in fat and cholesterol-free",
      "Suitable for vegetarians and vegans",
      "Easy to digest",
      "Versatile cooking ingredient",
    ],
    nutritionalInfo: {
      protein: "8g per 100g",
      fat: "4g per 100g",
      fiber: "2g per 100g",
      calories: "120 kcal per 100g",
    },
    highlight: [
      "High protein",
      "Low fat",
      "Cholesterol-free",
      "Vegan-friendly",
    ],
    keyFeatures: [
      "Rich source of plant-based protein",
      "Low in fat and cholesterol-free",
      "Suitable for vegetarians and vegans",
      "Easy to digest",
      "Versatile cooking ingredient",
      "Preservative Free",
    ],
    rating: 4.3,
    reviews: 85,
    subcategory: "Plain Tofu",
    expire: "7 days",
    wigthType: ["200 g", "400 g", "1 kg"],
  },
  {
    id: "raw-soya-milk",
    image: soyaMilkImg,
    name: "Raw Soya Milk",
    unit: "1 ltr",
    price: 148,
    description:
      "Enriched with vital nutrients of soya. It offers a delightful taste with various health benefits.",
    aboutProduct:
      "Our Raw Soya Milk is freshly prepared from carefully selected soybeans, preserving all natural nutrients and flavors. This wholesome beverage provides a pure, unprocessed alternative to traditional dairy milk with enhanced nutritional benefits.",
    button: "ADD",
    category: "Milk",
    discount: 15,
    detailedDescription:
      "Our Raw Soya Milk is freshly prepared from carefully selected soybeans, providing a nutritious and delicious alternative to dairy milk. Rich in essential nutrients and naturally lactose-free.",
    benefits: [
      "Rich in essential nutrients",
      "Lactose-free",
      "Naturally cholesterol-free",
      "Good source of calcium",
      "Supports heart health",
    ],
    nutritionalInfo: {
      protein: "7g per 100ml",
      fat: "3.5g per 100ml",
      fiber: "1g per 100ml",
      calories: "80 kcal per 100ml",
    },
    highlight: ["Rich nutrients", "Lactose-free", "Heart healthy", "Natural"],
    keyFeatures: [
      "Enriched with vital nutrients of soya",
      "Lactose-free alternative to dairy milk",
      "Naturally cholesterol-free",
      "Good source of calcium",
      "Supports heart health",
      "Freshly prepared",
    ],
    rating: 4.4,
    reviews: 120,
    subcategory: "Raw Milk",
    expire: "5 days",
    wigthType: ["500 ml", "1 ltr", "2 ltr"],
  },
  {
    id: "plain-curd-lactose-free",
    image: curdImg,
    name: "Plain Curd Lactose Free",
    unit: "400 g",
    price: 100,
    description:
      "Perfect combination of health & taste. It provides calcium for strong bones and teeth.",
    aboutProduct:
      "Our Plain Curd is specially formulated to be lactose-free while maintaining the authentic taste and creamy texture of traditional curd. Perfect for those with lactose sensitivity who don't want to compromise on taste or nutrition.",
    button: "ADD",
    category: "Curd",
    discount: 10,
    detailedDescription:
      "Our Plain Curd is specially prepared to be lactose-free while maintaining the authentic taste and texture of traditional curd. Perfect for those with lactose intolerance.",
    benefits: [
      "Lactose-free",
      "Rich in calcium",
      "Supports gut health",
      "Strengthens bones and teeth",
      "Natural probiotic properties",
    ],
    nutritionalInfo: {
      protein: "5g per 100g",
      fat: "3g per 100g",
      calcium: "150mg per 100g",
      calories: "70 kcal per 100g",
    },
    highlight: ["Lactose-free", "Rich calcium", "Gut health", "Probiotic"],
    keyFeatures: [
      "Specially prepared lactose-free curd",
      "Rich in calcium for strong bones",
      "Supports gut health",
      "Natural probiotic properties",
      "Strengthens bones and teeth",
      "Perfect for lactose intolerance",
    ],
    rating: 4.2,
    reviews: 95,
    subcategory: "Plain Curd",
    expire: "7 days",
    wigthType: ["200 g", "400 g", "1 kg"],
  },
  {
    id: "vanilla-ice-cream",
    image: vanillaImg,
    name: "Vanilla Ice Cream",
    unit: "700 ml",
    price: 210,
    description:
      "Rich Creamy Vanilla Dessert. Made from best ingredients: Fresh 100% soya milk.",
    aboutProduct:
      "Indulge in our creamy Vanilla Ice Cream crafted from 100% fresh soya milk. This dairy-free delight offers the perfect balance of sweetness and creaminess, making it an ideal treat for everyone, including those with lactose intolerance.",
    button: "ADD",
    category: "Ice Cream",
    discount: 25,
    detailedDescription:
      "Indulge in our creamy Vanilla Ice Cream made from 100% fresh soya milk. This dairy-free delight offers the perfect balance of sweetness and creaminess without compromising on taste.",
    benefits: [
      "Made from 100% soya milk",
      "Dairy-free",
      "Rich and creamy texture",
      "Natural vanilla flavor",
      "Suitable for lactose-intolerant individuals",
    ],
    nutritionalInfo: {
      protein: "4g per 100g",
      fat: "8g per 100g",
      sugar: "15g per 100g",
      calories: "180 kcal per 100g",
    },
    highlight: [
      "Dairy-free",
      "Creamy texture",
      "Natural vanilla",
      "Lactose-free",
    ],
    keyFeatures: [
      "Made from 100% fresh soya milk",
      "Dairy-free dessert option",
      "Rich and creamy texture",
      "Natural vanilla flavor",
      "Suitable for lactose-intolerant individuals",
      "Perfect balance of sweetness",
    ],
    rating: 4.6,
    reviews: 150,
    subcategory: "Vanilla Ice Cream",
    expire: "30 days",
    wigthType: ["350 ml", "700 ml", "1 ltr"],
  },
  {
    id: "chocolate-soya-milk",
    image: chocolateImg,
    name: "Chocolate Soya Milk",
    unit: "400 g",
    price: 100,
    description:
      "Perfect combination of health & taste. It provides calcium for strong bones and teeth.",
    aboutProduct:
      "Our Chocolate Soya Milk combines the nutritional benefits of soya with the irresistible taste of chocolate. A perfect blend of health and indulgence that makes getting your daily nutrients a delicious experience for the whole family.",
    button: "ADD",
    category: "Milk",
    discount: 15,
    detailedDescription:
      "Our Chocolate Soya Milk combines the nutritional benefits of soya with the delicious taste of chocolate. A perfect blend of health and indulgence for chocolate lovers.",
    benefits: [
      "Rich in protein and calcium",
      "Lactose-free",
      "Delicious chocolate flavor",
      "Supports bone health",
      "Perfect for kids and adults",
    ],
    nutritionalInfo: {
      protein: "6g per 100ml",
      fat: "3g per 100ml",
      sugar: "8g per 100ml",
      calories: "85 kcal per 100ml",
    },
    highlight: [
      "Chocolate flavor",
      "Rich protein",
      "Lactose-free",
      "Bone health",
    ],
    keyFeatures: [
      "Perfect blend of health and indulgence",
      "Rich in protein and calcium",
      "Lactose-free chocolate milk",
      "Delicious chocolate flavor",
      "Supports bone health",
      "Perfect for kids and adults",
    ],
    rating: 4.5,
    reviews: 110,
    subcategory: "Chocolate Milk",
    expire: "7 days",
    wigthType: ["250 ml", "400 ml", "1 ltr"],
  },
  {
    id: "plain-cheese",
    image: cheeseImg,
    name: "Plain Cheese",
    unit: "200 g",
    price: 420,
    description:
      "Perfect option for those with lactose intolerance, enjoy cheese without digestive discomfort.",
    aboutProduct:
      "Our Plain Cheese is specially crafted for those with lactose intolerance, offering the authentic taste and texture of traditional cheese without any digestive discomfort. Made from premium soya milk, it's perfect for cooking, grilling, or enjoying as a snack.",
    button: "ADD",
    category: "Cheese",
    discount: 30,
    detailedDescription:
      "Our Plain Cheese is specially crafted for those with lactose intolerance, offering the authentic taste and texture of traditional cheese without the digestive discomfort.",
    benefits: [
      "Lactose-free",
      "High in protein",
      "Rich in calcium",
      "Versatile cooking ingredient",
      "Supports bone health",
    ],
    nutritionalInfo: {
      protein: "25g per 100g",
      fat: "20g per 100g",
      calcium: "800mg per 100g",
      calories: "280 kcal per 100g",
    },
    highlight: ["Lactose-free", "High protein", "Rich calcium", "Versatile"],
    keyFeatures: [
      "Specially crafted for lactose intolerance",
      "High in protein content",
      "Rich in calcium",
      "Versatile cooking ingredient",
      "Supports bone health",
      "Authentic cheese taste",
    ],
    rating: 4.4,
    reviews: 130,
    subcategory: "Plain Cheese",
    expire: "14 days",
    wigthType: ["100 g", "200 g", "500 g"],
  },
  {
    id: "natural-yogurt",
    image: yogurtImg,
    name: "Natural Yogurt",
    unit: "400 g",
    price: 250,
    description:
      "Rich in protein | Low fat content. Made with natural ingredients. Perfect blend of taste & nutrition.",
    aboutProduct:
      "Our Natural Yogurt is crafted with the finest natural ingredients, offering a perfect blend of taste and nutrition. Rich in protein and low in fat, it's an ideal choice for health-conscious individuals who want to enjoy delicious yogurt without compromising on their dietary goals.",
    button: "ADD",
    category: "Yogurt",
    discount: 20,
    detailedDescription:
      "Our Natural Yogurt is made with the finest natural ingredients, offering a perfect blend of taste and nutrition. Rich in protein and low in fat, it's an ideal choice for health-conscious individuals.",
    benefits: [
      "Rich in protein",
      "Low fat content",
      "Natural ingredients",
      "Supports digestive health",
      "Boosts immunity",
    ],
    nutritionalInfo: {
      protein: "6g per 100g",
      fat: "2g per 100g",
      calcium: "200mg per 100g",
      calories: "90 kcal per 100g",
    },
    highlight: ["Rich protein", "Low fat", "Natural", "Immunity boost"],
    keyFeatures: [
      "Made with finest natural ingredients",
      "Rich in protein content",
      "Low fat content",
      "Supports digestive health",
      "Boosts immunity",
      "Perfect blend of taste and nutrition",
    ],
    rating: 4.3,
    reviews: 105,
    subcategory: "Natural Yogurt",
    expire: "10 days",
    wigthType: ["200 g", "400 g", "1 kg"],
  },
  {
    id: "soya-chakli",
    image: chakliImg,
    name: "Soya Chakli",
    unit: "100 g",
    price: 159,
    description:
      "Soya sticks, or boondi. Made with low-carb ingredients, healthy snack option for any time.",
    aboutProduct:
      "Our Soya Chakli is a healthy twist on traditional snacks, made with soya flour and low-carb ingredients. Perfect for guilt-free snacking any time of the day, it offers the familiar taste of traditional chakli with added nutritional benefits.",
    button: "ADD",
    category: "Namkeen",
    discount: 15,
    detailedDescription:
      "Our Soya Chakli is a healthy twist on traditional snacks, made with soya flour and low-carb ingredients. Perfect for guilt-free snacking any time of the day.",
    benefits: [
      "Low-carb ingredients",
      "Healthy snack option",
      "Rich in protein",
      "Suitable for diabetics",
      "No artificial preservatives",
    ],
    nutritionalInfo: {
      protein: "12g per 100g",
      fat: "8g per 100g",
      fiber: "5g per 100g",
      calories: "160 kcal per 100g",
    },
    highlight: [
      "Low-carb",
      "Healthy snack",
      "High protein",
      "Diabetic-friendly",
    ],
    keyFeatures: [
      "Healthy twist on traditional snacks",
      "Made with soya flour and low-carb ingredients",
      "Rich in protein content",
      "Suitable for diabetics",
      "No artificial preservatives",
      "Perfect for guilt-free snacking",
    ],
    rating: 4.1,
    reviews: 75,
    subcategory: "Soya Chakli",
    expire: "45 days",
    wigthType: ["100 g", "250 g", "500 g"],
  },
  {
    id: "herbal-tofu",
    image: herbalTofuImg,
    name: "Herbal Tofu",
    unit: "200 g",
    price: 110,
    description:
      "Easy to digest. High in protein and very low in fat. Great substitute of meat.",
    aboutProduct:
      "Our Herbal Tofu is infused with natural herbs and spices, making it easy to digest while providing high protein content with very low fat. An excellent meat substitute for vegetarians that adds both nutrition and flavor to your meals.",
    button: "ADD",
    category: "Tofu",
    discount: 10,
    detailedDescription:
      "Our Herbal Tofu is infused with natural herbs and spices, making it easy to digest while providing high protein content with very low fat. An excellent meat substitute for vegetarians.",
    benefits: [
      "Easy to digest",
      "High in protein",
      "Very low in fat",
      "Great meat substitute",
      "Infused with natural herbs",
    ],
    nutritionalInfo: {
      protein: "10g per 100g",
      fat: "2g per 100g",
      fiber: "3g per 100g",
      calories: "110 kcal per 100g",
    },
    highlight: ["Easy digest", "High protein", "Low fat", "Herbal infused"],
    keyFeatures: [
      "Infused with natural herbs and spices",
      "Easy to digest",
      "High protein content",
      "Very low in fat",
      "Great meat substitute",
      "Excellent for vegetarians",
    ],
    rating: 4.2,
    reviews: 90,
    subcategory: "Herbal Tofu",
    expire: "7 days",
    wigthType: ["200 g", "400 g", "1 kg"],
  },
  {
    id: "strawberry-ice-cream",
    image: strawberryIceCreamImg,
    name: "Strawberry Ice Cream",
    unit: "700 ml",
    price: 210,
    description:
      "Rich Creamy strawberry Dessert. Made from best ingredients: Fresh 100% soya milk.",
    aboutProduct:
      "Enjoy our creamy Strawberry Ice Cream made from 100% fresh soya milk. Bursting with natural strawberry flavor, this dairy-free dessert is perfect for strawberry lovers who want to indulge without compromising on their dietary preferences.",
    button: "ADD",
    category: "Ice Cream",
    discount: 25,
    detailedDescription:
      "Enjoy our creamy Strawberry Ice Cream made from 100% fresh soya milk. Bursting with natural strawberry flavor, this dairy-free dessert is perfect for strawberry lovers.",
    benefits: [
      "Made from 100% soya milk",
      "Dairy-free",
      "Natural strawberry flavor",
      "Rich and creamy texture",
      "Suitable for lactose-intolerant individuals",
    ],
    nutritionalInfo: {
      protein: "4g per 100g",
      fat: "8g per 100g",
      sugar: "16g per 100g",
      calories: "185 kcal per 100g",
    },
    highlight: ["Strawberry flavor", "Dairy-free", "Natural", "Lactose-free"],
    keyFeatures: [
      "Made from 100% fresh soya milk",
      "Bursting with natural strawberry flavor",
      "Dairy-free dessert option",
      "Rich and creamy texture",
      "Suitable for lactose-intolerant individuals",
      "Perfect for strawberry lovers",
    ],
    rating: 4.7,
    reviews: 140,
    subcategory: "Strawberry Ice Cream",
    expire: "30 days",
    wigthType: ["350 ml", "700 ml", "1 ltr"],
  },
  // Popular products
  {
    id: "cheese",
    image: p1,
    name: "CHEESE",
    unit: "200 g",
    price: 325,
    oldPrice: 420,
    description:
      "Premium quality cheese made from soya milk, perfect for cooking and direct consumption.",
    aboutProduct:
      "Our premium Cheese is crafted from high-quality soya milk, offering the authentic taste and texture of traditional cheese. Perfect for cooking, grilling, or enjoying as a snack, it provides all the culinary versatility you expect from cheese without any dairy-related concerns.",
    button: "ADD",
    category: "Cheese",
    discount: 23,
    detailedDescription:
      "Our premium Cheese is crafted from high-quality soya milk, offering the authentic taste and texture of traditional cheese. Perfect for cooking, grilling, or enjoying as a snack.",
    benefits: [
      "Premium quality",
      "High in protein",
      "Rich in calcium",
      "Versatile usage",
      "Lactose-free option",
    ],
    nutritionalInfo: {
      protein: "22g per 100g",
      fat: "18g per 100g",
      calcium: "750mg per 100g",
      calories: "260 kcal per 100g",
    },
    highlight: ["Premium quality", "High protein", "Rich calcium", "Versatile"],
    keyFeatures: [
      "Crafted from high-quality soya milk",
      "Premium quality cheese",
      "High in protein content",
      "Rich in calcium",
      "Versatile usage for cooking",
      "Lactose-free option",
    ],
    rating: 4.5,
    reviews: 160,
    subcategory: "Premium Cheese",
    expire: "14 days",
    wigthType: ["100 g", "200 g", "500 g"],
  },
  {
    id: "raw-milk",
    image: p2,
    name: "RAW MILK",
    unit: "1 ltr",
    price: 105,
    oldPrice: 148,
    description:
      "Fresh raw soya milk, rich in nutrients and perfect for daily consumption.",
    aboutProduct:
      "Our Raw Milk is freshly extracted from premium soybeans, preserving all natural nutrients and flavors. A wholesome beverage perfect for daily consumption that provides pure, unprocessed nutrition in its most natural form.",
    button: "ADD",
    category: "Milk",
    discount: 29,
    detailedDescription:
      "Our Raw Milk is freshly extracted from premium soybeans, preserving all natural nutrients and flavors. A wholesome beverage perfect for daily consumption.",
    benefits: [
      "Freshly extracted",
      "Rich in nutrients",
      "Natural flavor",
      "No artificial additives",
      "Perfect for daily consumption",
    ],
    nutritionalInfo: {
      protein: "8g per 100ml",
      fat: "4g per 100ml",
      fiber: "1.5g per 100ml",
      calories: "85 kcal per 100ml",
    },
    highlight: [
      "Freshly extracted",
      "Rich nutrients",
      "Natural",
      "Daily consumption",
    ],
    keyFeatures: [
      "Freshly extracted from premium soybeans",
      "Preserves all natural nutrients",
      "Rich in essential nutrients",
      "Natural flavor without additives",
      "No artificial additives",
      "Perfect for daily consumption",
    ],
    rating: 4.6,
    reviews: 180,
    subcategory: "Raw Milk",
    expire: "5 days",
    wigthType: ["500 ml", "1 ltr", "2 ltr"],
  },
  {
    id: "paneer",
    image: p3,
    name: "PANEER",
    unit: "200 g",
    price: 95,
    oldPrice: 110,
    description:
      "Fresh soya paneer, high in protein and perfect for Indian cooking.",
    aboutProduct:
      "Our fresh Soya Paneer is made from premium soybeans, offering high protein content and perfect texture for Indian cooking. A healthy alternative to traditional dairy paneer that maintains the authentic taste and cooking properties you love.",
    button: "ADD",
    category: "Paneer",
    discount: 14,
    detailedDescription:
      "Our fresh Soya Paneer is made from premium soybeans, offering high protein content and perfect texture for Indian cooking. A healthy alternative to traditional dairy paneer.",
    benefits: [
      "High in protein",
      "Perfect for Indian cooking",
      "Fresh and natural",
      "Easy to cook",
      "Versatile ingredient",
    ],
    nutritionalInfo: {
      protein: "15g per 100g",
      fat: "6g per 100g",
      fiber: "2g per 100g",
      calories: "140 kcal per 100g",
    },
    highlight: ["High protein", "Indian cooking", "Fresh natural", "Easy cook"],
    keyFeatures: [
      "Made from premium soybeans",
      "High protein content",
      "Perfect texture for Indian cooking",
      "Fresh and natural ingredients",
      "Easy to cook with",
      "Versatile ingredient",
    ],
    rating: 4.4,
    reviews: 125,
    subcategory: "Fresh Paneer",
    expire: "7 days",
    wigthType: ["200 g", "400 g", "1 kg"],
  },
  {
    id: "yogurt",
    image: p4,
    name: "YOGURT",
    unit: "400 g",
    price: 195,
    oldPrice: 250,
    description:
      "Natural soya yogurt, rich in probiotics and perfect for healthy living.",
    aboutProduct:
      "Our Natural Soya Yogurt is rich in probiotics and essential nutrients, making it perfect for maintaining a healthy lifestyle. Made with natural ingredients and no artificial preservatives, it supports your digestive health while providing delicious taste.",
    button: "ADD",
    category: "Yogurt",
    discount: 22,
    detailedDescription:
      "Our Natural Soya Yogurt is rich in probiotics and essential nutrients, making it perfect for maintaining a healthy lifestyle. Made with natural ingredients and no artificial preservatives.",
    benefits: [
      "Rich in probiotics",
      "Natural ingredients",
      "Supports gut health",
      "Boosts immunity",
      "Perfect for healthy living",
    ],
    nutritionalInfo: {
      protein: "7g per 100g",
      fat: "3g per 100g",
      calcium: "180mg per 100g",
      calories: "95 kcal per 100g",
    },
    highlight: [
      "Rich probiotics",
      "Natural ingredients",
      "Gut health",
      "Immunity boost",
    ],
    keyFeatures: [
      "Rich in probiotics and essential nutrients",
      "Made with natural ingredients",
      "Supports gut health",
      "Boosts immunity",
      "No artificial preservatives",
      "Perfect for healthy living",
    ],
    rating: 4.3,
    reviews: 115,
    subcategory: "Natural Yogurt",
    expire: "10 days",
    wigthType: ["200 g", "400 g", "1 kg"],
  },
];

// Export categories for filtering
export const categories = [
  "Cheese",
  "Milk",
  "Tofu",
  "Yogurt",
  "Curd",
  "Ice Cream",
  "Namkeen",
  "Paneer",
];

// Export sort options
export const sortOptions = [
  "Popularity",
  "Low to High",
  "High to Low",
  "Discount",
];

// Export discount options
export const discountOptions = [
  "50% or more",
  "40% or more",
  "30% or more",
  "20% or more",
  "10% or more",
];
